// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('T1', async function() {
    // Test name: T1
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/ | 
    await driver.get("http://localhost:5500/")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | mouseDownAt | id=drawingCanvas | 265.3999938964844,93.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 4 | mouseMoveAt | id=drawingCanvas | 265.3999938964844,93.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseUpAt | id=drawingCanvas | 265.3999938964844,93.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 6 | click | id=drawingCanvas | 
    await driver.findElement(By.id("drawingCanvas")).click()
    // 7 | click | css=.toolbar-button:nth-child(4) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(4)")).click()
    // 8 | assertAlert | Canvas saved successfully! | 
    assert(await driver.switchTo().alert().getText() == "Canvas saved successfully!")
    // 9 | assertElementPresent | id=drawingCanvas | 
    {
      const elements = await driver.findElements(By.id("drawingCanvas"))
      assert(elements.length)
    }
  })
  it('T2', async function() {
    // Test name: T2
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/about.html | 
    await driver.get("http://localhost:5500/about.html")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | click | css=li:nth-child(2) | 
    await driver.findElement(By.css("li:nth-child(2)")).click()
    // 4 | click | linkText=Home | 
    await driver.findElement(By.linkText("Home")).click()
    // 5 | click | id=colorPicker | 
    await driver.findElement(By.id("colorPicker")).click()
    // 6 | check | id=colorPicker | 
    {
      const element = await driver.findElement(By.id("colorPicker"))
      if (!(await element.isSelected())) await element.click()
    }
  })
  it('T4', async function() {
    // Test name: T4
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/ | 
    await driver.get("http://localhost:5500/")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
    // 4 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
    // 5 | mouseDownAt | id=drawingCanvas | 667.3999938964844,297.3999938964844
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 6 | mouseMoveAt | id=drawingCanvas | 667.3999938964844,297.3999938964844
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | mouseUpAt | id=drawingCanvas | 667.3999938964844,297.3999938964844
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 8 | click | id=drawingCanvas | 
    await driver.findElement(By.id("drawingCanvas")).click()
    // 9 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
    // 10 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
    // 11 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
    // 12 | click | css=.toolbar-button:nth-child(7) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(7)")).click()
  })
  it('T3', async function() {
    // Test name: T3
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/ | 
    await driver.get("http://localhost:5500/")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | mouseDownAt | id=drawingCanvas | 362.3999938964844,102.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 4 | mouseMoveAt | id=drawingCanvas | 362.3999938964844,102.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseUpAt | id=drawingCanvas | 362.3999938964844,102.39999389648438
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 6 | click | id=drawingCanvas | 
    await driver.findElement(By.id("drawingCanvas")).click()
    // 7 | click | id=clearButton | 
    await driver.findElement(By.id("clearButton")).click()
    // 8 | click | id=clearButton | 
    await driver.findElement(By.id("clearButton")).click()
  })
  it('T5', async function() {
    // Test name: T5
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/ | 
    await driver.get("http://localhost:5500/")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | mouseDownAt | id=drawingCanvas | 578.3999938964844,58.399993896484375
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 4 | mouseMoveAt | id=drawingCanvas | 578.3999938964844,58.399993896484375
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseUpAt | id=drawingCanvas | 578.3999938964844,58.399993896484375
    {
      const element = await driver.findElement(By.id("drawingCanvas"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 6 | click | id=drawingCanvas | 
    await driver.findElement(By.id("drawingCanvas")).click()
    // 7 | click | css=.toolbar-button:nth-child(4) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(4)")).click()
    // 8 | assertAlert | Canvas saved successfully! | 
    assert(await driver.switchTo().alert().getText() == "Canvas saved successfully!")
    // 9 | click | id=clearButton | 
    await driver.findElement(By.id("clearButton")).click()
    // 10 | click | css=.toolbar-button:nth-child(5) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(5)")).click()
    // 11 | assertElementPresent | id=clearButton | 
    {
      const elements = await driver.findElements(By.id("clearButton"))
      assert(elements.length)
    }
  })
  it('T6', async function() {
    // Test name: T6
    // Step # | name | target | value
    // 1 | open | http://localhost:5500/ | 
    await driver.get("http://localhost:5500/")
    // 2 | setWindowSize | 1107x912 | 
    await driver.manage().window().setRect({ width: 1107, height: 912 })
    // 3 | click | css=.toolbar-button:nth-child(5) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(5)")).click()
    // 4 | click | css=.toolbar-button:nth-child(5) | 
    await driver.findElement(By.css(".toolbar-button:nth-child(5)")).click()
    // 5 | assertElementPresent | css=.toolbar-button:nth-child(5) | 
    {
      const elements = await driver.findElements(By.css(".toolbar-button:nth-child(5)"))
      assert(elements.length)
    }
  })
})
